######################################################################
# Automatically generated by qmake (1.06c) Sun Oct 3 19:37:41 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .
LIBS += -lGLU

# Input
HEADERS += ../nehewidget.h ch10.h
SOURCES += main.cpp ../nehewidget.cpp
