install.packages('plyr')
library(plyr)

setwd("~/Documents/Learning/R/2")
zodiac_data = read.table("ZodiacChallenge.csv", header=TRUE, sep=",")
a = count(zodiac_data, "ZODIAK")
educated_subset = count(subset(zodiac_data, !(EDUCATION == "HS-grad" | EDUCATION == "1st-4th" | EDUCATION == "5th-6th" | EDUCATION == "7th-8th" | EDUCATION == "9th" | EDUCATION == "10th" | EDUCATION == "11th" | EDUCATION == "12th")), 'ZODIAK')
private_sector_subset = count(subset(zodiac_data, STATUS == "Private"), 'ZODIAK')
cg_1 = subset(zodiac_data, ZODIAK == "Aquarius")
cg_2 = subset(zodiac_data, ZODIAK == "Cancer")
cg_3 = subset(zodiac_data, ZODIAK == "Capricorn")
cg_4 = subset(zodiac_data, ZODIAK == "Gemini")
cg_5 = subset(zodiac_data, ZODIAK == "Leo")
cg_6 = subset(zodiac_data, ZODIAK == "Libra")
cg_7 = subset(zodiac_data, ZODIAK == "Libra")
cg_8 = subset(zodiac_data, ZODIAK == "Pisces")
cg_9 = subset(zodiac_data, ZODIAK == "Sagittarius")
cg_10 = subset(zodiac_data, ZODIAK == "Scorpio")
cg_11 = subset(zodiac_data, ZODIAK == "Virgo")

barplot(educated_subset$freq, main="Zodiacs in higher education", names.arg=educated_subset$ZODIAK)
barplot(private_sector_subset$freq, main="Zodiacs in the private sector", names.arg=private_sector_subset$ZODIAK)
cgs = c(sum(cg_1$CAPITALGAINS), sum(cg_2$CAPITALGAINS), sum(cg_3$CAPITALGAINS), sum(cg_4$CAPITALGAINS), sum(cg_5$CAPITALGAINS), sum(cg_6$CAPITALGAINS), sum(cg_7$CAPITALGAINS), sum(cg_8$CAPITALGAINS), sum(cg_9$CAPITALGAINS), sum(cg_10$CAPITALGAINS), sum(cg_11$CAPITALGAINS))
cls = c(sum(cg_1$CAPITALLOSS), sum(cg_2$CAPITALLOSS), sum(cg_3$CAPITALLOSS), sum(cg_4$CAPITALLOSS), sum(cg_5$CAPITALLOSS), sum(cg_6$CAPITALLOSS), sum(cg_7$CAPITALLOSS), sum(cg_8$CAPITALLOSS), sum(cg_9$CAPITALLOSS), sum(cg_10$CAPITALLOSS), sum(cg_11$CAPITALLOSS))
barplot(cgs, main="Capital gains by Zodiac", names.arg=private_sector_subset$ZODIAK)
barplot(cls, main="Capital loss by Zodiac", names.arg=private_sector_subset$ZODIAK)